name: open_polito_api
description: An open source, unofficial API for Politecnico di Torino.
version: 1.1.6
repository: https://github.com/open-polito/open_polito_api_dart

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  lints: ^2.0.0
  test: ^1.21.0
